name: Test Docker Build and Push

on:
  workflow_dispatch: # Allows you to manually trigger the workflow
  push: # Triggers on push to the main branch
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t hi .
          docker tag hi ghcr.io/nicolasluduena/package-1:latest
          docker tag hi ghcr.io/nicolasluduena/package-2:latest

      # Push the Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/nicolasluduena/package-1:latest
          docker push ghcr.io/nicolasluduena/package-2:latest
